use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use crate::json::Json;

use super::project::ProjectConfig;

pub(crate) fn write(
    root: &Path,
    config: &ProjectConfig,
    dry_run: bool,
) -> Result<Vec<String>, String> {
    let mut created = Vec::new();

    write_agents_md(root, config, dry_run, &mut created)?;
    write_plugin(root, config, dry_run, &mut created)?;

    Ok(created)
}

fn write_agents_md(
    root: &Path,
    config: &ProjectConfig,
    dry_run: bool,
    created: &mut Vec<String>,
) -> Result<(), String> {
    let content = format!(
        "{}\n{}\n",
        HEADER,
        config.build_self_contained().trim_end()
    );
    write_file(root, "AGENTS.md", &content, dry_run, created)
}

fn write_plugin(
    root: &Path,
    config: &ProjectConfig,
    dry_run: bool,
    created: &mut Vec<String>,
) -> Result<(), String> {
    let plugin_dir = format!(".agents/plugins/{}", config.name);

    if !dry_run {
        let full = root.join(&plugin_dir);
        if full.exists() {
            fs::remove_dir_all(&full)
                .map_err(|e| format!("failed to remove {plugin_dir}: {e}"))?;
        }
    }

    // plugin.json
    let plugin_json = Json::Object({
        let mut m = BTreeMap::new();
        m.insert("name".to_string(), Json::Str(config.name.clone()));
        m
    });
    write_file(
        root,
        &format!("{plugin_dir}/plugin.json"),
        &plugin_json.to_pretty_string(),
        dry_run,
        created,
    )?;

    // mcp_config.json
    if !config.mcp_servers.is_empty() {
        let mut mcp_map = BTreeMap::new();
        for (name, server) in &config.mcp_servers {
            let mut entry = BTreeMap::new();
            entry.insert("command".to_string(), Json::Str(server.command.clone()));
            if !server.args.is_empty() {
                entry.insert(
                    "args".to_string(),
                    Json::Array(server.args.iter().map(|a| Json::Str(a.clone())).collect()),
                );
            }
            if !server.env.is_empty() {
                let env_map: BTreeMap<String, Json> = server
                    .env
                    .iter()
                    .map(|(k, v)| (k.clone(), Json::Str(v.clone())))
                    .collect();
                entry.insert("env".to_string(), Json::Object(env_map));
            }
            if let Some(cwd) = &server.cwd {
                entry.insert("cwd".to_string(), Json::Str(cwd.clone()));
            }
            if server.disabled {
                entry.insert("disabled".to_string(), Json::Bool(true));
            }
            mcp_map.insert(name.clone(), Json::Object(entry));
        }

        let mcp_json = Json::Object({
            let mut m = BTreeMap::new();
            m.insert("mcpServers".to_string(), Json::Object(mcp_map));
            m
        });
        write_file(
            root,
            &format!("{plugin_dir}/mcp_config.json"),
            &mcp_json.to_pretty_string(),
            dry_run,
            created,
        )?;
    }

    // rules/ — self-contained instructions
    let instructions = format!(
        "{}\n{}\n",
        HEADER,
        config.build_self_contained().trim_end()
    );
    write_file(
        root,
        &format!("{plugin_dir}/rules/{}-instructions.md", config.name),
        &instructions,
        dry_run,
        created,
    )?;

    // commands/ — copy of source commands
    for cmd in &config.commands {
        write_file(
            root,
            &format!("{plugin_dir}/commands/{}", cmd.rel_path),
            &cmd.body,
            dry_run,
            created,
        )?;
    }

    Ok(())
}

fn write_file(
    root: &Path,
    rel: &str,
    content: &str,
    dry_run: bool,
    created: &mut Vec<String>,
) -> Result<(), String> {
    if dry_run {
        created.push(format!("(dry-run) {rel}"));
        return Ok(());
    }
    let path = root.join(rel);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("failed to create {}: {e}", parent.display()))?;
    }
    fs::write(&path, content).map_err(|e| format!("failed to write {}: {e}", path.display()))?;
    created.push(rel.to_string());
    Ok(())
}

const HEADER: &str =
    "<!-- AUTO-GENERATED by par convert — do not edit. Edit source files, then re-run: par convert -->";
