use std::fs;
use std::path::Path;

use super::project::ProjectConfig;
use super::util::{clean_generated_skills, skill_dir_name, truncate, GENERATED_MARKER};

pub(crate) fn write(
    root: &Path,
    config: &ProjectConfig,
    dry_run: bool,
) -> Result<Vec<String>, String> {
    let mut created = Vec::new();

    write_agents_md(root, config, dry_run, &mut created)?;
    write_codex_config_toml(root, config, dry_run, &mut created)?;
    write_agents_skills(root, config, dry_run, &mut created)?;

    Ok(created)
}

fn write_agents_md(
    root: &Path,
    config: &ProjectConfig,
    dry_run: bool,
    created: &mut Vec<String>,
) -> Result<(), String> {
    let content = format!(
        "{}\n{}\n",
        HEADER,
        config.build_self_contained().trim_end()
    );
    write_file(root, "AGENTS.md", &content, dry_run, created)
}

fn write_codex_config_toml(
    root: &Path,
    config: &ProjectConfig,
    dry_run: bool,
    created: &mut Vec<String>,
) -> Result<(), String> {
    let mut toml = String::from("# AUTO-GENERATED by par convert — do not edit.\n\n");
    toml.push_str("project_doc_fallback_filenames = [\"CLAUDE.md\"]\n");

    if !config.mcp_servers.is_empty() {
        toml.push('\n');
        for (name, server) in &config.mcp_servers {
            let key = name.replace('-', "_");
            toml.push_str(&format!("[mcp_servers.{key}]\n"));
            toml.push_str(&format!(
                "enabled = {}\n",
                if server.disabled { "false" } else { "true" }
            ));
            toml.push_str(&format!("command = {:?}\n", server.command));

            let args: Vec<String> = server.args.iter().map(|a| format!("{a:?}")).collect();
            toml.push_str(&format!("args = [{}]\n", args.join(", ")));

            if let Some(cwd) = &server.cwd {
                toml.push_str(&format!("cwd = {cwd:?}\n"));
            }
            if !server.env.is_empty() {
                let entries: Vec<String> = server
                    .env
                    .iter()
                    .map(|(k, v)| format!("{k:?} = {v:?}"))
                    .collect();
                toml.push_str(&format!("env = {{ {} }}\n", entries.join(", ")));
            }
            toml.push('\n');
        }
    }

    if !dry_run {
        fs::create_dir_all(root.join(".codex"))
            .map_err(|e| format!("failed to create .codex: {e}"))?;
    }
    write_file(root, ".codex/config.toml", &toml, dry_run, created)
}

fn write_agents_skills(
    root: &Path,
    config: &ProjectConfig,
    dry_run: bool,
    created: &mut Vec<String>,
) -> Result<(), String> {
    if config.commands.is_empty() {
        return Ok(());
    }

    if !dry_run {
        clean_generated_skills(&root.join(".agents/skills"))?;
    }

    for cmd in &config.commands {
        let skill_name = skill_dir_name(&cmd.name);
        let command_name = format!("/{}", cmd.name);
        let desc = if cmd.description.starts_with("Run ") {
            cmd.description.clone()
        } else {
            format!("Run {command_name}: {}", cmd.description)
        };
        let desc = truncate(&desc, 240);

        let skill_content = format!(
            "---\nname: {skill_name}\ndescription: |\n  {desc}\n# {GENERATED_MARKER}\n---\n\n# {command_name}\n\nUse this skill when the user asks to run `{command_name}`.\n\n{}\n",
            cmd.body.trim(),
            GENERATED_MARKER = GENERATED_MARKER,
        );

        write_file(
            root,
            &format!(".agents/skills/{skill_name}/SKILL.md"),
            &skill_content,
            dry_run,
            created,
        )?;
    }

    Ok(())
}

fn write_file(
    root: &Path,
    rel: &str,
    content: &str,
    dry_run: bool,
    created: &mut Vec<String>,
) -> Result<(), String> {
    if dry_run {
        created.push(format!("(dry-run) {rel}"));
        return Ok(());
    }
    let path = root.join(rel);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("failed to create {}: {e}", parent.display()))?;
    }
    fs::write(&path, content).map_err(|e| format!("failed to write {}: {e}", path.display()))?;
    created.push(rel.to_string());
    Ok(())
}

const HEADER: &str =
    "<!-- AUTO-GENERATED by par convert — do not edit. Edit source files, then re-run: par convert -->";
