use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use crate::json::Json;

use super::project::ProjectConfig;

pub(crate) fn write(root: &Path, config: &ProjectConfig, dry_run: bool) -> Result<Vec<String>, String> {
    let mut created = Vec::new();

    write_gemini_md(root, config, dry_run, &mut created)?;
    write_gemini_commands(root, config, dry_run, &mut created)?;
    write_gemini_settings(root, config, dry_run, &mut created)?;

    Ok(created)
}

fn write_gemini_md(
    root: &Path,
    config: &ProjectConfig,
    dry_run: bool,
    created: &mut Vec<String>,
) -> Result<(), String> {
    let content = format!(
        "{}\n{}\n",
        HEADER,
        config.build_self_contained().trim_end()
    );
    write_file(root, "GEMINI.md", &content, dry_run, created)
}

fn write_gemini_commands(
    root: &Path,
    config: &ProjectConfig,
    dry_run: bool,
    created: &mut Vec<String>,
) -> Result<(), String> {
    let dir = root.join(".gemini/commands");
    if !dry_run {
        if dir.exists() {
            fs::remove_dir_all(&dir)
                .map_err(|e| format!("failed to remove .gemini/commands: {e}"))?;
        }
        fs::create_dir_all(&dir)
            .map_err(|e| format!("failed to create .gemini/commands: {e}"))?;
    }

    for cmd in &config.commands {
        let toml_rel = cmd.rel_path.trim_end_matches(".md").to_string() + ".toml";
        let toml_path = format!(".gemini/commands/{toml_rel}");
        let desc = cmd.description.replace('"', "\\\"");
        let body = cmd.body.trim_end();

        let content = format!(
            "description = \"{desc}\"\nprompt = \"\"\"\nPlease execute the instructions in the following file:\n{body}\n\nUser arguments: {{{{args}}}}\n\"\"\"\n"
        );
        write_file(root, &toml_path, &content, dry_run, created)?;
    }

    Ok(())
}

fn write_gemini_settings(
    root: &Path,
    config: &ProjectConfig,
    dry_run: bool,
    created: &mut Vec<String>,
) -> Result<(), String> {
    if config.mcp_servers.is_empty() {
        return Ok(());
    }

    let mut mcp_map = BTreeMap::new();
    for (name, server) in &config.mcp_servers {
        let mut entry = BTreeMap::new();
        entry.insert("command".to_string(), Json::Str(server.command.clone()));
        entry.insert(
            "args".to_string(),
            Json::Array(server.args.iter().map(|a| Json::Str(a.clone())).collect()),
        );
        entry.insert("trust".to_string(), Json::Bool(true));
        mcp_map.insert(name.clone(), Json::Object(entry));
    }

    let mut tools = BTreeMap::new();
    let mut shell_opts = BTreeMap::new();
    shell_opts.insert(
        "enableToolOutputTruncation".to_string(),
        Json::Bool(true),
    );
    shell_opts.insert(
        "toolOutputTruncationThreshold".to_string(),
        Json::Number(200000.0),
    );
    shell_opts.insert(
        "toolOutputTruncationLines".to_string(),
        Json::Number(1000.0),
    );
    tools.insert("run_shell_command".to_string(), Json::Object(shell_opts));

    let mut top = BTreeMap::new();
    top.insert("tools".to_string(), Json::Object(tools));
    top.insert("mcpServers".to_string(), Json::Object(mcp_map));

    let json = Json::Object(top);
    let dir = root.join(".gemini");
    if !dry_run {
        fs::create_dir_all(&dir)
            .map_err(|e| format!("failed to create .gemini: {e}"))?;
    }
    write_file(root, ".gemini/settings.json", &json.to_pretty_string(), dry_run, created)
}

fn write_file(
    root: &Path,
    rel: &str,
    content: &str,
    dry_run: bool,
    created: &mut Vec<String>,
) -> Result<(), String> {
    if dry_run {
        created.push(format!("(dry-run) {rel}"));
        return Ok(());
    }
    let path = root.join(rel);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("failed to create {}: {e}", parent.display()))?;
    }
    fs::write(&path, content).map_err(|e| format!("failed to write {}: {e}", path.display()))?;
    created.push(rel.to_string());
    Ok(())
}

const HEADER: &str =
    "<!-- AUTO-GENERATED by par convert — do not edit. Edit source files, then re-run: par convert -->";
